### ISSUE TITLE
대구 -> 통영 국도 영상 결과 데이터 도출 위한 추가 아이디어 필요

### ISSUE THREAD

**Issue by sadcookie** [CUDSnSLab/Image_Classifier#1]
현재)
미탐지 : 포트홀 잇는데 안잡은 경우
정상탐지 : 포트홀 있는데 잡은 경우
오류탐지(오탐지, false postive) : 포트홀 없는데 잡은경우

결과 데이터 로그 작성법
 - 프레임 번호,  ROI 내 오브젝트 개수, 위험 오브젝트 탐지한 사각형 개수, 연속되는 오브젝트의 경우 별도 라벨링

탐지 결과 예시
 - 미탐지:  224, 2,  0, 223번과 연속됨
 - 정상탐지:  345,2,  2, 없음
 - 오류탐지:  450,null,  null, null  

 예상 결과 데이터 
 -미탐지, 정상탐지, 오류탐지 결과 획득

**Comment by KwangEun** [comment]
이 이슈는 제목과 내용 불일치 및 포맷 불일치와 관리에 대한 내용으로서 이슈 의도와 맞지 않아 닫음.
이슈로 남길 내용은 두고 진행 내용에 대한 것은 GitHub Project를 사용 하도록 요청.

정정내용 :  
* 이슈 제목 포맷 사용 
* 내용 중 추가 아이디어 관련된 토의 내용은 토의 내용 항목에 대하여 명확하게 명시
* 연속되는 오브젝트 및 오류탐지에 대한 정확한 정의 내용 추가. 예로 오류탐지가 False Positive 인지 True Negative 인지
